# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat_App
    pod 'SocketRocket'
    pod 'FMDB'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DKImagePickerController'
    pod 'SDWebImage'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'

  target 'Chat_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Chat_AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
